### ISSUE TITLE
[bug] Any Modded Anvil Instantly Closes Reforge Menu

### ISSUE THREAD

**Issue by PixelatedBruh** [Andrew6rant/Tiered#9]
As soon as you click the tab it closes the anvil menu completely.

**Comment by Andrew6rant** [comment]
This sounds like it is an issue for TieredZ (another fork of the original Tiered), and not this mod. There are no Anvil tabs in my fork of Tiered, I made the reforging station a new block.

**Comment by PixelatedBruh** [comment]
My apologies I had made this issue very late at night. sorry to have used your time incorrectly.
